### ISSUE TITLE
Error on ~shutdown n

### ISSUE THREAD

**Issue by PointyDev** [jaydenkieran/Turbo#9]
When shutting down with ~shutdown n, it throws an error into console. The bot was configured to run as a selfbot. The following test was run on [master 46c6af7](https://github.com/jaydenkieran/Turbo/tree/46c6af7bb6d7285255a26e3c4be457d866cd9a21) after running [updatedeps-win.bat](https://github.com/jaydenkieran/Turbo/blob/master/updatedeps-win.bat):

Log:
```
Turbo (2.0). Connecting...
Logged in as Pointy#2414 (99914384989519872)

Configuration:
- Selfbot: yes
- Allow PMs: yes
- Prefix: ~

RethinkDB:
- Connecting to database...
- Established connection. Server: PointlessnessPC_0c7


Bot is ready.

[Command] Pointy#2414 [Pointy's Test Server | #general] - ~shutdown
[Command] Pointy#2414 [Pointy's Test Server | #general] - ~shutdown n
```
Error:
```python
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0433AAB0>
```
Screenshot:
![ss 2016-09-20 at 06 23 27](https://cloud.githubusercontent.com/assets/22241432/18681415/e01eeacc-7f5f-11e6-9d2f-fcf8fe2126c3.png)

**Comment by jaydenkieran** [comment]
This isn't really an error, just more of a telling off from `aiohttp` that I didn't close the client session properly. As such though, it is a small annoyance, so I just pushed a commit to the `nightly` branch to fix this: https://github.com/jaydenkieran/Turbo/commit/25f24ea5a7933b2b6338efc970cd6725d53bfbd3

Cheers!
